<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED version-major CDATA #REQUIRED version-minor CDATA #REQUIRED version-git CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED label CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED><!ATTLIST buffer-attribute name CDATA #REQUIRED>]><context name="local" version-major="0" version-minor="25" version-git="v0.25" description="Linux SberBoom-Home-3349 6.15.11-sdkernel #1 SMP PREEMPT Tue May 26 10:48:20 UTC 2026 aarch64" ><context-attribute name="local,kernel" value="6.15.11-sdkernel" /><context-attribute name="uri" value="local:" /><device id="hwmon0" name="soc_thermal" ><channel id="temp1" type="input" ><attribute name="input" filename="temp1_input" /></channel></device><device id="iio:device0" name="hx3203-21" ><channel id="intensity_both" type="input" ><scan-element index="0" format="le:u18/32&gt;&gt;0" /><attribute name="raw" filename="in_intensity_both_raw" /></channel><channel id="intensity_ir" type="input" ><scan-element index="1" format="le:u18/32&gt;&gt;0" /><attribute name="raw" filename="in_intensity_ir_raw" /></channel><channel id="illuminance0" type="input" ><scan-element index="2" format="le:u18/32&gt;&gt;0" /><attribute name="input" filename="in_illuminance0_input" /></channel><channel id="timestamp" type="input" ><scan-element index="3" format="le:S64/64&gt;&gt;0" /></channel><attribute name="current_timestamp_clock" /><attribute name="integration_time" /><attribute name="integration_time_available" /><attribute name="scale" /><attribute name="scale_available" /><attribute name="waiting_for_supplier" /><buffer-attribute name="data_available" /><buffer-attribute name="direction" /><debug-attribute name="direct_reg_access" /></device></context>
